# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0003_auto_20180201_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='exam2.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='exam2.User'),
        ),
    ]
