# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0004_auto_20180201_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorites',
        ),
        migrations.AddField(
            model_name='quote',
            name='users',
            field=models.ManyToManyField(related_name='quotes', to='exam2.User'),
        ),
    ]
