# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0005_auto_20180201_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='users',
        ),
        migrations.AddField(
            model_name='quote',
            name='faved_users',
            field=models.ManyToManyField(null=True, related_name='faved_quotes', to='exam2.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='exam2.User'),
        ),
    ]
