# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0006_auto_20180201_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='faved_users',
            field=models.ManyToManyField(related_name='faved_quotes', to='exam2.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='exam2.User'),
        ),
    ]
