# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0008_auto_20180201_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='faved_users',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
